# Generated by Django 4.2.6 on 2024-01-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Utilisateur',
        ),
    ]
