# Generated by Django 4.2.6 on 2024-01-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0006_album_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
