# Generated by Django 4.2.6 on 2024-01-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0008_utilisateur_groups_utilisateur_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_staff',
        ),
    ]
