# Generated by Django 4.2.6 on 2024-01-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0012_utilisateur_groups_utilisateur_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
